@extends('monitor.layouts.master')
@section('title', __('Installation terms of use and privacy policy'))
@section('description', __("Installation terms of use and privacy policy"))
@section('main')
<main class="pt-16 max-w-3xl mx-auto px-6 py-12 text-gray-800 leading-relaxed">
    <article class="mb-12">
        <h2 class="text-2xl font-bold mb-4 text-gray-900">🛡️ @lang('Terms of Use and Privacy Policy for Laravel Monitor Package')</h2>
        <p class="mb-3">
            @lang('By installing and using the Laravel Monitor package (the &quot;Package&quot;), you agree to the following terms and the privacy policy, which govern how the Package interacts with your Laravel application for the purpose of security monitoring, performance, and anti-scraper combat').
        </p>
    </article>
    <article class="mb-12">
        <h2 class="text-2xl font-bold mb-4 text-gray-900">1. @lang('Creation of Communication Tokens')</h2>
        <p class="mb-3">@lang('To ensure security and efficient communication between the different parts of the system (your backend application and the frontend monitoring interface), the Package will generate and use communication tokens').</p>
        <p class="mb-2"><span class="font-semibold">@lang('Purpose'):</span> @lang('These tokens are strictly used to authenticate and authorize access to our monitoring interface, allowing you to view the data and metrics generated by the Package').</p>
        <p class="mb-2"><span class="font-semibold">@lang('Security'):</span> @lang('The use of these tokens is a standard security measure to ensure that only you have access to your monitoring panel').</p>
    </article>
    <article class="mb-12">
        <h2 class="text-2xl font-bold mb-4 text-gray-900">2. @lang('No Storage and No Access to User Data')</h2>
        <p class="mb-3">@lang('The Package was developed with the premise of privacy and complete data control by the end-user (you, the Package installer)').</p>
        <p class="mb-2"><span class="font-semibold">@lang('Data Storage'):</span> @lang('The Package DOES NOT store any user, site, or monitoring data on external servers. All data collected for monitoring (logs, metrics, etc.) are stored directly in your own database (Laravel Database) or in other resources within your infrastructure, according to the configurations you define').</p>
        <p class="mb-2"><span class="f  ont-semibold">@lang('Data Access'):</span> @lang('The Package DOES NOT access, manipulate, or send the data from your application to us or to third parties. Access to monitoring data to populate the frontend interface is done directly via internal Package APIs within your own application, ensuring that the data flow remains entirely under your control').</p>
    </article>
    <article class="mb-12">
        <h2 class="text-2xl font-bold mb-4 text-gray-900">3. @lang('User Responsibility (You)')</h2>
        <p class="mb-3">@lang('By using the Package, you assume the responsibility to'):</p>
        <p class="mb-2"><span class="font-semibold">@lang('Inform Your Visitors'):</span> @lang('You must clearly inform the visitors of your websites that the visit to the site collects data for the purpose of security, monitoring, and prevention of fraud/attacks (anti-scraper). It is recommended to include this information in your own Privacy Policy and/or Terms of Use').</p>
        <p class="mb-2"><span class="font-semibold">@lang('Legal Compliance'):</span> @lang('It is your responsibility to ensure that the data collection for monitoring by the Package is in compliance with all applicable data protection laws and regulations in your jurisdiction (e.g., LGPD in Brazil, GDPR in Europe, etc.)').</p>
    </article>
    <article class="mb-12">
        <p class="mb-3">@lang('By proceeding with the installation, you confirm that you have read and understood these terms').</p>
    </article>
    <div class="text-center mt-12">
        <a href="{{ url('/') }}"
        class="inline-block bg-gray-800 text-white px-6 py-3 rounded-xl shadow hover:bg-gray-700 transition">
            @lang('Return to home page')
        </a>
    </div>
</main>

@endsection
